version: 2

sources:
  - name: raw_data_circle # Kaynak takma ad
    database: cankat-my-new-project # Proje ID
    schema: raw_data_circle # BigQuery Dataset adı
    tables:
      - name: raw_cc_parcel
      - name: raw_cc_parcel_product
