with source as (
  -- Burada source fonksiyonu ile ham veriye bağlanıyoruz
  select * from {{ source('gz_raw_data', 'raw_gz_sales') }}
),

renamed as (
  select
    date_date,
    orders_id,
    pdt_id,
    revenue,
    quantity
  from source
)

-- En sonda, yukarıda temizlediğin 'renamed' CTE'sini çağırmalısın
select * from renamed